// <auto-generated />
using System;
using LogicaDatos.Repositorios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaDatos.Migrations
{
    [DbContext(typeof(ObligatorioContext))]
    [Migration("20240511194232_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.Dominio.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProveedor")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Articulos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoProveedor = "1234567890123",
                            Descripcion = "Calculadora de bolsillo Casio",
                            Nombre = "Calculadora Casio",
                            Precio = 300,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CodigoProveedor = "1234567890124",
                            Descripcion = "500 hojas para imprimir en formato A4",
                            Nombre = "Resma A4",
                            Precio = 250,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CodigoProveedor = "1234567890125",
                            Descripcion = "Bluetooth o conexión USB, cable desmontable",
                            Nombre = "Auriculares con Micrófono",
                            Precio = 500,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            CodigoProveedor = "1234567890126",
                            Descripcion = "Soporte lumbar, altura ajustable y base giratoria con ruedas",
                            Nombre = "Silla De Escritorio",
                            Precio = 3200,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DistanciaHastaDeposito")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("Rut")
                        .IsUnique()
                        .HasFilter("[Rut] IS NOT NULL");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanciaHastaDeposito = 98,
                            RazonSocial = "PF",
                            Rut = "123456789012"
                        },
                        new
                        {
                            Id = 2,
                            DistanciaHastaDeposito = 101,
                            RazonSocial = "LZ",
                            Rut = "987654321098"
                        },
                        new
                        {
                            Id = 3,
                            DistanciaHastaDeposito = 96,
                            RazonSocial = "TWS",
                            Rut = "111222333444"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Linea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("PreciodUnitario")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesSolicitadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Lineas", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Parametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Parametros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "IVA",
                            Valor = 0.18m
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pedido");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Admin",
                            Contraseña = "Passw0rd!",
                            Email = "admin@admin.com",
                            Nombre = "Sys",
                            Tipo = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Planta",
                            Contraseña = "Passw0rd!",
                            Email = "rplanta@lz.com",
                            Nombre = "Roberto",
                            Tipo = "Estandar"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.PedidoComun", b =>
                {
                    b.HasBaseType("LogicaNegocio.Dominio.Pedido");

                    b.Property<int>("PlazoEstipulado")
                        .HasColumnType("int");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PedidoComun");
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.PedidoExpress", b =>
                {
                    b.HasBaseType("LogicaNegocio.Dominio.Pedido");

                    b.Property<int>("PlazoEstipulado")
                        .HasColumnType("int");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Pedidos", t =>
                        {
                            t.Property("PlazoEstipulado")
                                .HasColumnName("PedidoExpress_PlazoEstipulado");

                            t.Property("Recargo")
                                .HasColumnName("PedidoExpress_Recargo");
                        });

                    b.HasDiscriminator().HasValue("PedidoExpress");
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Cliente", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("int");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");

                            b1.OwnsOne("LogicaNegocio.ValueObjects.Calle", "Calle", b2 =>
                                {
                                    b2.Property<int>("DireccionId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("DireccionId");

                                    b2.ToTable("Clientes");

                                    b2.WithOwner()
                                        .HasForeignKey("DireccionId");

                                    b2.HasData(
                                        new
                                        {
                                            DireccionId = 1,
                                            Valor = "Ciudadela"
                                        },
                                        new
                                        {
                                            DireccionId = 2,
                                            Valor = "Reconquista"
                                        },
                                        new
                                        {
                                            DireccionId = 3,
                                            Valor = "Durazno"
                                        });
                                });

                            b1.OwnsOne("LogicaNegocio.ValueObjects.Ciudad", "Ciudad", b2 =>
                                {
                                    b2.Property<int>("DireccionId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("DireccionId");

                                    b2.ToTable("Clientes");

                                    b2.WithOwner()
                                        .HasForeignKey("DireccionId");

                                    b2.HasData(
                                        new
                                        {
                                            DireccionId = 1,
                                            Valor = "Montevideo"
                                        },
                                        new
                                        {
                                            DireccionId = 2,
                                            Valor = "Montevideo"
                                        },
                                        new
                                        {
                                            DireccionId = 3,
                                            Valor = "Montevideo"
                                        });
                                });

                            b1.OwnsOne("LogicaNegocio.ValueObjects.NumeroPuerta", "NumeroPuerta", b2 =>
                                {
                                    b2.Property<int>("DireccionId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("DireccionId");

                                    b2.ToTable("Clientes");

                                    b2.WithOwner()
                                        .HasForeignKey("DireccionId");

                                    b2.HasData(
                                        new
                                        {
                                            DireccionId = 1,
                                            Valor = "1180"
                                        },
                                        new
                                        {
                                            DireccionId = 2,
                                            Valor = "600"
                                        },
                                        new
                                        {
                                            DireccionId = 3,
                                            Valor = "902"
                                        });
                                });

                            b1.Navigation("Calle")
                                .IsRequired();

                            b1.Navigation("Ciudad")
                                .IsRequired();

                            b1.Navigation("NumeroPuerta")
                                .IsRequired();

                            b1.HasData(
                                new
                                {
                                    ClienteId = 1
                                },
                                new
                                {
                                    ClienteId = 2
                                },
                                new
                                {
                                    ClienteId = 3
                                });
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Linea", b =>
                {
                    b.HasOne("LogicaNegocio.Dominio.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Dominio.Pedido", null)
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoId");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Pedido", b =>
                {
                    b.HasOne("LogicaNegocio.Dominio.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Pedido", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
